# Generated by Django 6.1 on 2026-08-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFailover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('taxa_erro', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_failover', to='clientes.instancia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('falhou', 'Falhou (aguardando nova tentativa)'), ('falha_definitiva', 'Falha definitiva')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('max_tentativas', models.PositiveIntegerField(default=3)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='campanhas.campanha')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='contatos.contato')),
                ('instancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='clientes.instancia')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'proxima_tentativa_em'], name='envios_envi_status_61d1d8_idx')],
            },
        ),
    ]
