# Generated by Django 6.1 on 2026-08-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('round_robin', models.BooleanField(default=True, help_text='Intercalar envios entre as instâncias vinculadas.')),
                ('segmentacao_tipo', models.CharField(choices=[('todos', 'Todos os contatos'), ('tag', 'Por tag'), ('lista', 'Lista específica')], default='todos', max_length=10)),
                ('limite_envios_dia', models.PositiveIntegerField(default=500)),
                ('tamanho_lote', models.PositiveIntegerField(default=5, help_text='Mensagens disparadas seguidas antes de pausar.')),
                ('delay_min_segundos', models.PositiveIntegerField(default=3, help_text='Delay mínimo entre mensagens do mesmo lote.')),
                ('delay_max_segundos', models.PositiveIntegerField(default=8, help_text='Delay máximo entre mensagens do mesmo lote.')),
                ('pausa_entre_lotes_segundos', models.PositiveIntegerField(default=120, help_text='Descanso entre uma rajada e a próxima.')),
                ('delay_sequencia_segundos', models.PositiveIntegerField(default=3, help_text='Intervalo entre os itens de uma mesma mensagem (texto → imagem → vídeo) para um contato.')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('dias_semana_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de dias permitidos (0=Segunda .. 6=Domingo). Vazio = todos os dias.')),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='clientes.cliente')),
                ('instancias', models.ManyToManyField(related_name='campanhas', to='clientes.instancia')),
                ('segmentacao_contatos', models.ManyToManyField(blank=True, related_name='campanhas_lista', to='contatos.contato')),
                ('segmentacao_tags', models.ManyToManyField(blank=True, related_name='campanhas', to='contatos.tag')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio')], max_length=10)),
                ('texto', models.TextField(blank=True, help_text='Legenda ou corpo do texto (usado em texto/imagem/vídeo).')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='campanhas/midias/')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='campanhas.campanha')),
            ],
            options={
                'ordering': ['campanha', 'ordem'],
            },
        ),
    ]
