# Generated by Django 6.1 on 2026-08-25 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=32)),
                ('ativo', models.BooleanField(default=True)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('instance_id', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('client_token', models.CharField(blank=True, help_text='Token de segurança da conta Z-API (Client-Token), se configurado.', max_length=200)),
                ('status', models.CharField(choices=[('conectada', 'Conectada'), ('desconectada', 'Desconectada'), ('banida', 'Banida/erro'), ('pausada', 'Pausada (failover)')], default='desconectada', max_length=20)),
                ('pausada_ate', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacao_em', models.DateTimeField(blank=True, null=True)),
                ('janela_amostra', models.PositiveIntegerField(default=20, help_text='Quantos envios recentes analisar para calcular a taxa de erro.')),
                ('limite_taxa_erro', models.FloatField(default=0.3, help_text='Taxa de falha (0-1) na amostra que aciona a pausa automática.')),
                ('pausa_pos_failover_minutos', models.PositiveIntegerField(default=30, help_text='Minutos que a instância fica pausada após acionar o failover.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='clientes.cliente')),
            ],
            options={
                'ordering': ['cliente__nome', 'apelido'],
            },
        ),
    ]
