# Generated by Django 6.1 on 2026-08-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/origem/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_processadas', models.PositiveIntegerField(default=0)),
                ('total_validos', models.PositiveIntegerField(default=0)),
                ('total_duplicados', models.PositiveIntegerField(default=0)),
                ('total_invalidos', models.PositiveIntegerField(default=0)),
                ('relatorio_validos', models.FileField(blank=True, null=True, upload_to='importacoes/relatorios/')),
                ('relatorio_duplicados', models.FileField(blank=True, null=True, upload_to='importacoes/relatorios/')),
                ('relatorio_invalidos', models.FileField(blank=True, null=True, upload_to='importacoes/relatorios/')),
                ('relatorio_erros', models.FileField(blank=True, null=True, upload_to='importacoes/relatorios/')),
                ('erro_mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='clientes.cliente')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(help_text='Formato normalizado: DDI+DDD+número, só dígitos.', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente')),
                ('tags', models.ManyToManyField(blank=True, related_name='contatos', to='contatos.tag')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('cliente', 'telefone')},
            },
        ),
    ]
